INSERT INTO public.doctor(
	id, nume_doctor, id_departament, specializare)
	VALUES 
(1, 'Dr. Popescu', 1, 'Cardiologie'),
(2, 'Dr. Ionescu', 2, 'Chirurgie Generală'),
(3, 'Dr. Vasilescu', 4, 'Pediatrie'),
(4, 'Dr. Stanescu', 18, 'Neurologie'),
(5, 'Dr. Radulescu', 28, 'Ginecologie'),
(6, 'Dr. Andreea Popa', 11, 'Ortopedie'),
(7, 'Dr. Mircea Grigorescu', 16, 'Endocrinologie'),
(8, 'Dr. Elena Stoica', 8, 'Oftalmologie'),
(9, 'Dr. Maria Tanase', 9, 'Psihiatrie'),
(10, 'Dr. Adrian Munteanu', 2, 'Radiologie'),
(11, 'Dr. Bianca Popovici', 17, 'Nefrologie'),
(12, 'Dr. Alexandru Georgescu', 10, 'Dermatologie'),
(13, 'Dr. Carmen Dumitrescu', 3, 'Urgențe'),
(14, 'Dr. Ionut Marinescu', 23, 'Hematologie'),
(15, 'Dr. Ana Constantinescu', 13, 'Gastroenterologie'),
(16, 'Dr. Mihai Iordache', 15, 'Pneumologie'),
(17, 'Dr. Roxana Stan', 6, 'Oncologie'),
(18, 'Dr. Daniel Costache', 12, 'Reumatologie'),
(19, 'Dr. Gabriela Neagu', 14, 'Infecțioase'),
(20, 'Dr. Adrian Diaconu', 20, 'Chirurgie Plastică'),
(21, 'Dr. Elena Popoviciu', 21, 'Geriatrie'),
(22, 'Dr. Ionut Moldovan', 22, 'Nefrologie Pediatrică'),
(23, 'Dr. Mihaela Radu', 7, 'Cardiologie Pediatrică'),
(24, 'Dr. Andrei Marinescu', 24, 'Psihiatrie Infantilă'),
(25, 'Dr. Ana Maria Vasilescu', 25, 'Otorinolaringologie'),
(26, 'Dr. Vlad Andrei', 26, 'Medicină Internă'),
(27, 'Dr. Ioana Petrescu', 27, 'Neurologie Pediatrică'),
(28, 'Dr. Adrian Dragomir', 31, 'Chirurgie Vasculară'),
(29, 'Dr. Irina Stanescu', 29, 'Pediatrie Oncologică'),
(30, 'Dr. Radu Popa', 30, 'Endoscopie'),
(31, 'Dr. Adrian Radulescu', 1, 'Cardiologie'),
(32, 'Dr. Alina Andreescu', 32, 'Pneumologie Pediatrică'),
(33, 'Dr. Mihai Tudor', 33, 'Diabetologie'),
(34, 'Dr. Ana Maria Popescu', 34, 'Neonatologie'),
(35, 'Dr. Elena Stan', 35, 'Urologie'),
(36, 'Dr. Andrei Popa', 36, 'Traumatologie'),
(37, 'Dr. Camelia Ionescu', 37, 'Ginecologie Oncologică'),
(38, 'Dr. Cristian Mihai', 38, 'Imunologie'),
(39, 'Dr. Maria Ilie', 39, 'Endocrinologie Pediatrică'),
(40, 'Dr. Victor Radu', 40, 'Ortopedie Pediatrică'),
(41, 'Dr. Ana Maria Moldovan', 41, 'Hematologie Pediatrică'),
(42, 'Dr. Bogdan Pop', 42, 'Gastroenterologie Pediatrică'),
(43, 'Dr. Irina Stoica', 43, 'Reumatologie Pediatrică'),
(44, 'Dr. Radu Grigorescu', 44, 'Chirurgie Maxilo-Facială'),
(45, 'Dr. Elena Tudor', 45, 'Neurochirurgie'),
(46, 'Dr. Andrei Popescu', 46, 'Pediatrie Cardiologică'),
(47, 'Dr. Camelia Diaconu', 47, 'Dermato-Venerologie'),
(48, 'Dr. Bogdan Radu', 48, 'Chirurgie Plastică Reconstructivă'),
(49, 'Dr. Irina Munteanu', 49, 'Pediatrie Nefrologică'),
(50, 'Dr. Victor Dragomir', 50, 'Medicină de Familie');