INSERT INTO public.echipamente(
	id, spital_id, nume_echipament, stare)
	VALUES
(1, 1, 'Electrocardiograf', 'Funcțional'),
(2, 2, 'Aparat de Raze X', 'În mentenanță'),
(3, 3, 'Ecograf', 'Funcțional'),
(4, 4, 'Rezonanță Magnetică (RMN)', 'Funcțional'),
(5, 5, 'Monitor de Tensiune', 'Funcțional'),
(6, 6, 'Ventilator', 'În mentenanță'),
(7, 7, 'Defibrilator', 'Funcțional'),
(8, 8, 'Aparat de Anestezie', 'Funcțional'),
(9, 9, 'Luminile Chirurgicale', 'Funcțional'),
(10, 10, 'Pompa de Infuzie', 'În mentenanță'),
(11, 11, 'Endoscop', 'Funcțional'),
(12, 12, 'Aparat de Dializă', 'În mentenanță'),
(13, 13, 'Centrifugă de Laborator', 'Funcțional'),
(14, 14, 'Incubator', 'Funcțional'),
(15, 15, 'Autoclav', 'În mentenanță'),
(16, 16, 'Concentrator de Oxigen', 'Funcțional'),
(17, 17, 'Oximetru de Puls', 'Funcțional'),
(18, 18, 'Aparat de Raze X Portabil', 'În mentenanță'),
(19, 19, 'Monitor de Pacient', 'Funcțional'),
(20, 20, 'Unitate de Cauterizare', 'În mentenanță'),
(21, 21, 'Ultrasunete Portabil', 'Funcțional'),
(22, 22, 'Scaun Dentar', 'Funcțional'),
(23, 23, 'Tomograf Computerizat (CT)', 'În mentenanță'),
(24, 24, 'Analizor Hematologic', 'Funcțional'),
(25, 25, 'Sistem de Eliberare Medicamente', 'Funcțional'),
(26, 26, 'Foraj Ortopedic', 'În mentenanță'),
(27, 27, 'Microscop Chirurgical', 'Funcțional'),
(28, 28, 'Sistem de Radiografie Digitală', 'Funcțional'),
(29, 29, 'Înregistrător de Electrocardiogramă', 'În mentenanță'),
(30, 30, 'Incubator Neonatal', 'Funcțional'),
(31, 31, 'Monitor Holter EKG', 'Funcțional'),
(32, 32, 'Aparat de Ventilare non-invazivă', 'În mentenanță'),
(33, 33, 'Sistem de Diagnosticare Endoscopică', 'Funcțional'),
(34, 34, 'Aparat de Anestezie Inhalator', 'Funcțional'),
(35, 35, 'Microscop Operator', 'Funcțional'),
(36, 36, 'Sistem de Imagistică Nucleară', 'În mentenanță'),
(37, 37, 'Ecograf Portabil', 'Funcțional'),
(38, 38, 'Monitor Cardiac Implantabil', 'Funcțional'),
(39, 39, 'Sistem de Testare Sanguină', 'În mentenanță'),
(40, 40, 'Ventilator de Transport', 'Funcțional'),
(41, 41, 'Analizor de Gaze Sanguine', 'Funcțional'),
(42, 42, 'Aparat de Tomografie Dentală', 'În mentenanță'),
(43, 43, 'Aparat de Radiografie Panoramică', 'Funcțional'),
(44, 44, 'Ventilator cu Sistem de Căldură și Umidificare', 'În mentenanță'),
(45, 45, 'Monitor de Funcție Pulmonară', 'Funcțional'),
(46, 46, 'Sistem de Biopsie Asistată de Imagini', 'Funcțional'),
(47, 47, 'Defibrilator Automat Extern', 'În mentenanță'),
(48, 48, 'Aparat de Hemodializă', 'Funcțional'),
(49, 49, 'Laser Chirurgical', 'În mentenanță'),
(50, 50, 'Aparat de Ventilare cu Presiune Pozitivă', 'Funcțional');