INSERT INTO public.asistent_medical(
	id, id_departament, grad)
	VALUES 
(1, 1, 'Asist Med Generalist'),
(2, 2, 'Asist Med Generalist'),
(3, 4, 'Asist Med Pediatric'),
(4, 4, 'Asist Med Generalist'),
(5, 28, 'Asist Med Ginecologie'),
(6, 11, 'Asist Med Ortopedie'),
(7, 7, 'Asist Med Generalist'),
(8, 8, 'Asist Med Anestezie'),
(9, 9, 'Asist Med Psihiatrie'),
(10, 2, 'Asist Med Radiologie'),
(11, 22, 'Asist Med Nefrologie'),
(12, 10, 'Asist Med Dermatologie'),
(13, 13, 'Asist Med Urgențe'),
(14, 23, 'Asist Med Hematologie'),
(15, 13, 'Asist Med Gastroenterologie'),
(16, 15, 'Asist Med Pneumologie'),
(17, 6, 'Asist Med Oncologie'),
(18, 12, 'Asist Med Reumatologie'),
(19, 14, 'Asist Med Infecțioase'),
(20, 48, 'Asist Med Chirurgie Plastică'),
(21, 21, 'Asist Med Geriatrie'),
(22, 22, 'Asist Med Pediatric Nefrologie'),
(23, 46, 'Asist Med Pediatric Cardiologie'),
(24, 24, 'Asist Med Psihiatrie Infantilă'),
(25, 25, 'Asist Med Otorinolaringologie'),
(26, 26, 'Asist Med Medicină Internă'),
(27, 27, 'Asist Med Pediatric Neurologie'),
(28, 31, 'Asist Med Chirurgie Vasculară'),
(29, 29, 'Asist Med Pediatric Oncologie'),
(30, 30, 'Asist Med Endoscopie'),
(31, 31, 'Asist Med Cardiologie'),
(32, 32, 'Asist Med Pneumologie Pediatrică'),
(33, 33, 'Asist Med Diabetologie'),
(34, 34, 'Asist Med Neonatologie'),
(35, 35, 'Asist Med Urologie'),
(36, 36, 'Asist Med Traumatologie'),
(37, 37, 'Asist Med Ginecologie Oncologică'),
(38, 38, 'Asist Med Imunologie'),
(39, 39, 'Asist Med Endocrinologie Pediatrică'),
(40, 40, 'Asist Med Ortopedie Pediatrică'),
(41, 41, 'Asist Med Hematologie Pediatrică'),
(42, 42, 'Asist Med Gastroenterologie Pediatrică'),
(43, 43, 'Asist Med Reumatologie Pediatrică'),
(44, 44, 'Asist Med Chirurgie Maxilo-Facială'),
(45, 45, 'Asist Med Neurochirurgie'),
(46, 46, 'Asist Med Pediatrie Cardiologică'),
(47, 47, 'Asist Med Dermato-Venerologie'),
(48, 48, 'Asist Med Chirurgie Plastică Reconstructivă'),
(49, 49, 'Asist Med Pediatrie Nefrologică'),
(50, 50, 'Asist Med Medicină de Familie');